language: go

services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - TEST_DB_CONNECTION="user=postgres password='' host=127.0.0.1 port=5432 dbname=travis_ci_test sslmode='disable' bytea_output='hex'"
go:
  - 1.13.x
install:
  - go get github.com/mattn/goveralls
script:
  - psql -c  -U postgres
  - go test -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
